import DEFAULT_ENV_TEXT from './default-env-text'
import VARIANTS from './variants'
import {
  DEFAULT_PROGRESS_BAR_PERCENT,
  MAX_PROGRESS_BAR_PERCENT,
  MILLISECONDS_IN_A_SECOND,
  PROGRESS_BAR_TIMEOUT
} from './magic-numbers-collection'
import {
  HEX_COLOR_PRIMARY,
  HEX_COLOR_SECONDARY,
  HEX_COLOR_SUCCESS,
  HEX_COLOR_WARNING,
  HEX_COLOR_DANGER
} from './hex-colors'

export {
  DEFAULT_ENV_TEXT,
  VARIANTS,
  DEFAULT_PROGRESS_BAR_PERCENT,
  MAX_PROGRESS_BAR_PERCENT,
  MILLISECONDS_IN_A_SECOND,
  PROGRESS_BAR_TIMEOUT,
  HEX_COLOR_PRIMARY,
  HEX_COLOR_SECONDARY,
  HEX_COLOR_SUCCESS,
  HEX_COLOR_WARNING,
  HEX_COLOR_DANGER
}
